# Generated by Django 3.1 on 2021-09-11 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('video_link', models.TextField()),
                ('is_processed', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('scraping_name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Trie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.TextField()),
                ('viewcount', models.IntegerField(default=1)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('minute', models.IntegerField(default=0)),
                ('error', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.player')),
                ('team', models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, to='rugby.team')),
            ],
        ),
        migrations.CreateModel(
            name='TrieRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('trie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.trie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapedmatch_away_team', to='rugby.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapedmatch_home_team', to='rugby.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.league')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='player',
            name='internation_team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='h', to='rugby.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.team'),
        ),
        migrations.CreateModel(
            name='MatchRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_away_team', to='rugby.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='rugby.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.league'),
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_posted', models.BooleanField()),
                ('try_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.trie')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('error', models.IntegerField(choices=[(1, 'Incorrect Video'), (2, 'Match Cancelled')])),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errormatch_away_team', to='rugby.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errormatch_home_team', to='rugby.team')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.league')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
