# Generated by Django 2.2.4 on 2019-08-12 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('stadium', models.TextField()),
                ('ref', models.TextField()),
                ('attendance', models.IntegerField()),
                ('video_link', models.TextField()),
                ('league', models.TextField(default='super')),
                ('rd', models.IntegerField(default=1)),
                ('viewcount', models.IntegerField(default=1)),
                ('ratings_average', models.IntegerField(default=2)),
                ('tries_created', models.IntegerField(default=0)),
                ('tries_in_match', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('picture', models.TextField(default='hi')),
                ('coolfact', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField()),
                ('league', models.TextField(default='super')),
                ('logo', models.TextField()),
                ('primary_colour', models.TextField(default='#000000')),
                ('secondary_colour', models.TextField(default='#FFFFFF')),
            ],
        ),
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.TextField()),
                ('viewcount', models.IntegerField(default=1)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
                ('ratings_average', models.IntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='rugby.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='rugby.Team'),
        ),
    ]
