# Generated by Django 3.1 on 2021-09-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trie',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
