# Generated by Django 3.1 on 2021-09-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0002_trie_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='scraping_name',
            field=models.TextField(default='', null=True),
        ),
    ]
