# Generated by Django 2.2.4 on 2019-08-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0002_auto_20190812_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.TextField(default='super'),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.TextField(default='super'),
        ),
    ]
