# Generated by Django 3.1 on 2021-09-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0003_auto_20210912_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='internation_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
