# Generated by Django 2.2.4 on 2019-08-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0003_auto_20190812_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.RemoveField(
            model_name='try',
            name='id',
        ),
        migrations.AddField(
            model_name='match',
            name='match_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='try',
            name='try_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
