# Generated by Django 2.2.4 on 2019-08-12 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0004_auto_20190812_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='try',
            name='try_id',
        ),
        migrations.AddField(
            model_name='match',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='try',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='try',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rugby.Team'),
        ),
    ]
