# Generated by Django 2.2.4 on 2019-08-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0007_remove_try_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
    ]
