# Generated by Django 2.2.4 on 2019-08-15 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0013_auto_20190812_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='try',
            name='team',
        ),
        migrations.AddField(
            model_name='match',
            name='match_completely_processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='video_link_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='video_sliced',
            field=models.IntegerField(default=0),
        ),
    ]
