# Generated by Django 2.2.4 on 2019-08-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0015_try_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='coolfact',
            field=models.TextField(default='hi'),
        ),
    ]
