# Generated by Django 2.2.5 on 2019-10-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0020_auto_20191009_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Team'),
        ),
        migrations.AlterField(
            model_name='try',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rugby.Team'),
        ),
    ]
