# Generated by Django 2.2.5 on 2019-10-11 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0023_team_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='internation_team',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.CASCADE, related_name='h', to='rugby.Team'),
            preserve_default=False,
        ),
    ]
