# Generated by Django 2.2.5 on 2019-10-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0024_player_internation_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
