# Generated by Django 2.2.5 on 2019-10-11 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0025_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='league_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rugby.League'),
            preserve_default=False,
        ),
    ]
