# Generated by Django 2.2.5 on 2019-10-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0026_match_league_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league_id',
            field=models.TextField(default=1),
        ),
    ]
