# Generated by Django 2.1.13 on 2019-11-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0028_auto_20191011_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='video_not_found',
            field=models.IntegerField(default=0),
        ),
    ]
