# Generated by Django 2.2.4 on 2019-11-05 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0029_match_video_not_found'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='rugby.MatchRating'),
        ),
    ]
