# Generated by Django 2.2.4 on 2019-12-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0031_remove_match_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrating',
            name='userId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
