# Generated by Django 2.2.4 on 2019-12-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0032_matchrating_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrating',
            name='userId',
            field=models.TextField(),
        ),
    ]
