# Generated by Django 2.2.4 on 2019-12-13 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0033_auto_20191213_0551'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('userId', models.TextField()),
                ('try_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Match')),
            ],
        ),
    ]
