# Generated by Django 2.2.4 on 2019-12-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0034_tryrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tryrating',
            name='try_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.Try'),
        ),
    ]
