# Generated by Django 2.2.5 on 2019-12-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0036_try_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='player',
            name='coolfact',
        ),
        migrations.RemoveField(
            model_name='player',
            name='picture',
        ),
    ]
