# Generated by Django 2.2.5 on 2019-12-22 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0037_auto_20191222_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='internation_team',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='h', to='rugby.Team'),
        ),
    ]
