# Generated by Django 2.2.5 on 2020-01-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0038_auto_20191222_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ratings_average',
            field=models.IntegerField(default=0),
        ),
    ]
