# Generated by Django 2.2.5 on 2020-01-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0039_match_ratings_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ratings_average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='try',
            name='ratings_average',
            field=models.FloatField(default=0),
        ),
    ]
