# Generated by Django 2.2.5 on 2020-02-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0040_auto_20200109_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchrating',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='tryrating',
            name='userId',
        ),
    ]
