# Generated by Django 2.2.5 on 2020-07-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0041_auto_20200212_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='team',
            name='primary_colour',
        ),
        migrations.RemoveField(
            model_name='team',
            name='secondary_colour',
        ),
    ]
