# Generated by Django 2.2.5 on 2020-08-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0043_team_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='region_blocked',
            field=models.TextField(default=''),
        ),
    ]
