# Generated by Django 2.2.5 on 2020-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0045_try_elo_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='try',
            name='nz_elo_rating',
            field=models.IntegerField(default=1000),
        ),
    ]
