# Generated by Django 3.1 on 2020-11-08 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rugby', '0046_try_nz_elo_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_posted', models.BooleanField()),
                ('try_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rugby.try')),
            ],
        ),
    ]
